name: Deploy
on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  Build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build docker
        run: |
          rm -f .env
          printf "NEXT_PUBLIC_BASE_API_URL=https://datarace.ai/v1" > .env
          docker build -t datarace-web-prod .
          docker stop datarace-web-prod  || true
          docker rm datarace-web-prod || true
          docker run -p 3013:3000 -d --name=datarace-web-prod datarace-web-prod
